### ISSUE TITLE
Add CoC, Contributing file

### ISSUE THREAD

**Issue by FloorD** [jeroenoomsNL/recruitment-ipsum#1]
Hey @jeroenoomsNL 👋 Would you consider adding a Code of Conduct (template under `Insights` > `Community`) and a `CONTRIBUTING.md` file? In the latter you could put what you have in your README now in terms of env setup, as well as define what kind of contributions you're looking for, like recruitment email pet peeves of others, translations for recruitment ipsum in other languages, or maybe you're hoping someone builds a recruitment ipsum Twitter bot, VS Code or browser extension...?

**Comment by jeroenoomsNL** [comment]
Thanks for your advice Floor! I'll add this and I'm looking forward to your pullrequest ;-)
